source: .
destination: ./_site

title: "David Dias"
subtitle: "Front-End <span>User Experience</span> Developer"
description: "Personal website of front-end developer David Dias."
locale: "en_US"
noindex: false

repository: "daviddiasfront/daviddiasfront.github.io"
url: "https://www.david-dias.com"

# Site owner
owner:
  name: "David Dias"
  bio: ""
  avatar: "/avatar/david-dias.jpg"
  email: "daviddiasfront@gmail.com"
  social:
    img: ""
    twitter_username: "daviddiasfront"
    facebook_username: "daviddiasfront"
    instagram_username: "daviddiasfront"
    github_username: "daviddiasfront"
    codepen_username: "daviddiasfront"
    500px_username: "daviddiasfront"
    foursquare_username: "daviddiasfront"
    github_repo: "https://github.com/daviddiasfront/daviddiasfront.github.io/"
    github_master: "https://github.com/daviddiasfront/daviddiasfront.github.io/blob/master/"
  google:
    provider: "google-universal"
    analytics: "UA-45667748-1"
    plus: "https://plus.google.com/+DavidDiasFront/posts"
    verify: ""
  bing:
    verify: "84B7F071DD4BC580F678B80A9D62EED1"
  comments:
    provider: "disqus"
    disqus:
      shortname: "daviddiasfront"

# Jekyll configuration
future: false
show_drafts: false
markdown: kramdown
markdown: kramdown
kramdown:
  toc_levels: 1..3
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
highlighter: rouge
keep_files:
  - .git
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - _assets/img/icons

# Collections
collections:
  projects:
    output: true

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: _posts/notes
      type: posts
    values:
      permalink: /notes/:title/
      layout: post
      category: thought
      read_time: true
      comments: true
      share: true
      related: true
      author: David Dias
      breadcrumbs:
        - label: "Notes"
          url: /notes/
  # _posts
  - scope:
      path: _posts/experiments
      type: posts
    values:
      permalink: /experiments/:title/
      layout: post
      category: thought
      read_time: true
      comments: true
      share: true
      author: David Dias
      breadcrumbs:
        - label: "Experiments"
          url: /experiments/
  # _projects
  - scope:
      path: _projects
      type: projects
    values:
      permalink: /projects/:title/
      layout: project
      breadcrumbs:
        - label: "Projects"
          url: /projects/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

permalink: /admin/

# Jekyll archive configuration
jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag
    category: category
  permalinks:
    category: '/category/:name/'
    tag: /tag/:name/

jekyll-mentions:
  base_url: https://twitter.com

assets:

  autowrite: true
  prefix: "/assets"
  digest: true
  
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/img
    - _assets/js

gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-tagging-related_posts
  - jekyll/tagging


